### ISSUE TITLE
How hide expanded fabs without animation ?

### ISSUE THREAD

**Issue by ilwsm** [valdio/FloatingActionButton_Animation_Project#1]
How hide expanded fabs without animation (example, after click on small fab)?

**Comment by valdio** [comment]
You can always use 

fab.hide();
        fab.show();
        
        fab.setVisibility(View.GONE);

**Comment by valdio** [comment]
You can always use this methods  
        fab.hide();
        fab.show();

```
    or 

    fab.setVisibility(View.GONE);
```

**Comment by ilwsm** [comment]
Thanks, i will try

**Comment by ilwsm** [comment]
I think `fab.clearAnimation()` is better way )
